CREATE TABLE CUSTOMER_DIM (
    CUSTOMER_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    AGE INT,
    GENDER CHAR(1),
    PHONE VARCHAR(15),
    EMAIL VARCHAR(100),
    MARITAL_STATUS VARCHAR(20),
    HAS_CHILDREN BOOLEAN
);
CREATE TABLE PRODUCT_DIM (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    PRICE DECIMAL(10, 2)
);
CREATE TABLE PROMOTION_DIM (
    PROMOTION_ID INT PRIMARY KEY,
    PROMOTION_NAME VARCHAR(100),
    START_DATE DATE,
    END_DATE DATE,
    DISCOUNT DECIMAL(5, 2)
);
CREATE TABLE CASHIER_DIM (
    CASHIER_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    AGE INT,
    GENDER CHAR(1),
    PHONE VARCHAR(15),
    SALARY DECIMAL(10, 2),
    HIRE_DATE DATE
);
CREATE TABLE BRANCH_DIM (
    BRANCH_ID INT PRIMARY KEY,
    BRANCH_NAME VARCHAR(100),
    BRANCH_AREA VARCHAR(100),
    CITY_NAME VARCHAR(100),
    STATE_NAME VARCHAR(100)
);
CREATE TABLE CATEGORY_DIM (
    CATEGORY_ID INT PRIMARY KEY,
    SUB_ID INT,
    CATEGORY_NAME VARCHAR(100),
    SUB_CATEGORY_NAME VARCHAR(100)
);
CREATE TABLE DATE_DIM (
    DATE_ID INT PRIMARY KEY,
    DATE DATE,
    DAY_OF_WEEK VARCHAR(20),
    DAY_OF_MONTH INT,
    DAY_OF_YEAR INT,
    LAST_DAY_IN_MONTH_FLAG BOOLEAN,
    WEEK_NUMBER_IN_YEAR INT,
    MONTH_NAME VARCHAR(20),
    MONTH_NUMBER INT,
    QUARTER VARCHAR(10),
    YEAR INT,
    HOLIDAY_INDICATOR BOOLEAN,
    WEEKDAY_INDICATOR BOOLEAN
);
CREATE TABLE SALES_FACT (
    TRANSACTION_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    CASHIER_ID INT,
    BRANCH_ID INT,
    DATE_ID INT,
    PROMOTION_ID INT,
    CATEGORY_ID INT,
    QUANTITY INT,
    SALES_AMOUNT DECIMAL(10, 2),
    TIME TIME,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_DIM(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_DIM(PRODUCT_ID),
    FOREIGN KEY (CASHIER_ID) REFERENCES CASHIER_DIM(CASHIER_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH_DIM(BRANCH_ID),
    FOREIGN KEY (DATE_ID) REFERENCES DATE_DIM(DATE_ID),
    FOREIGN KEY (PROMOTION_ID) REFERENCES PROMOTION_DIM(PROMOTION_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY_DIM(CATEGORY_ID)
);